name: cd
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.HOSTNAME }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
      USER: ${{ secrets.USER }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "TOKEN=$TOKEN" > .env
      - run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keyscan -H "$HOSTNAME" >> ~/.ssh/known_hosts
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - run: ssh $USER@$HOSTNAME 'mkdir -p ~/$GITHUB_REPOSITORY/ && cd ~/$GITHUB_REPOSITORY/ && npm stop || true'
      - run: rsync -avz --exclude '.git' ./ $USER@$HOSTNAME:/home/$USER/$GITHUB_REPOSITORY/
      - run: ssh $USER@$HOSTNAME 'cd ~/$GITHUB_REPOSITORY/ && npm install && npm start'
