name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.IMAGE }}:latest,${{ secrets.IMAGE }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch task definition
        run: aws ecs describe-task-definition --task-definition ${{ secrets.SERVICE }} --query taskDefinition > task-definition.json

      - name: Render task definition
        id: render-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          container-name: app
          environment-variables: TOKEN=${{ secrets.TOKEN }}
          image: ${{ secrets.IMAGE }}:${{ github.sha }}
          task-definition: task-definition.json

      - name: Deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: ${{ secrets.CLUSTER }}
          service: ${{ secrets.SERVICE }}
          task-definition: ${{ steps.render-task.outputs.task-definition }}
          wait-for-service-stability: true
